### ISSUE TITLE
Overriding default style does not work

### ISSUE THREAD

**Issue by aaron-kunde** [AOEpeople/aoe_technology_radar#346]
1. Created new project, as described in documentation
2. Added custom `style.css` in folder `public/` as described, with conten
```
body {
  background-color: red: 
}
```
This has no effect, since the generated `main.xxxx.css` is loaded after the style.css. So styles set in `styles.css` are overridden by `main.xxxx.css`.

![grafik](https://user-images.githubusercontent.com/8394929/225372669-cfb080ff-382b-4531-b8ab-be7c0fab01cc.png)

**Comment by ugurkadam** [comment]
that's true, however, if you require a quick workaround for now you can always use the "!important" mark on your public CSS.

despite the "!important" usually being discouraged from using on the CSS styles, since that'll be custom styles added later on I'm guessing using "!important" shouldn't create so much of a problem here.

an example here;

```CSS
body {
    font-family: Roboto !important;
    line-height: 2.1 !important;
    background: #0cb3e6 !important;
}
````
