### ISSUE TITLE
custom.css - classes different on build and serve

### ISSUE THREAD

**Issue by derkoe** [AOEpeople/aoe_technology_radar#440]
I've tried the new `custom.css` feature and have struggled with it.

It seems that when running a build the class names are generated differently - for example `container__Layout_**` when running with `npm serve` becomes `Layout_container` when building the application.

As a workaround I have added both styles in my `custom.css`:
```css
[class^="container__Layout"],
[class^="Layout_container"] {
    background-color: #004985;
}
```

Maybe you can find a way around this with css-modules.
