### ISSUE TITLE
Logo disappears after altering CSS class

### ISSUE THREAD

**Issue by D1StrX** [AOEpeople/aoe_technology_radar#528]
I currently have this custom CSS in place. But the text without the `ItemDetail_release` is unreadable as seen below, hence the white text.
![Image](https://github.com/user-attachments/assets/6d5ea336-089b-473e-932d-aee2e738acb6)

![Image](https://github.com/user-attachments/assets/6945bc4c-fda0-4c9a-8909-c2527524fe0f) Logo

But for some reason the logo left top becomes unavailable. Any idea why this class causes that?

```css
body {
  background: #e0f7fa;
  color: #333333;
}

[class^="ItemDetail_release"] {
  color: white;
}

```
